apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: example
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: https://github.com/bjunker99/test-argo.git
    targetRevision: test
    ref: valuesrepo
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    from:
    - sourcePath: "$valuesrepo/environment/values.yaml"
      destinationPath: "env-values.yaml"  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
